### ISSUE TITLE
Use sphinx to generate docs?

### ISSUE THREAD

**Issue by malmans2** [MillionConcepts/lhorizon#14] opened 2021-08-09 10:44 UTC
If I'm understanding correctly, `api.md` is not automatically inferred from the actual code but was manually written.
I think it would be more robust to only use docstrings in the code, this way the api in the documentation is always up to date.
I suggest to look into [sphinx](https://www.sphinx-doc.org/en/master/), particularly the docstring extensions: [google style](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html), [numpy style](https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html#example-numpy)

https://github.com/openjournals/joss-reviews/issues/3495

**Comment by m-stclair** [comment] 2021-08-11 03:51
`api.md` is generated using `mkdocs` -- i prefer markdown docstrings to google or numpy-style docstrings for this project. I am, however, regenerating it only manually -- do you think it would be preferable to add a CI hook to rebuild the docs?

**Comment by malmans2** [comment] 2021-08-11 10:32
> do you think it would be preferable to add a CI hook to rebuild the docs?

Yes, I think that would be ideal. You could either add a github action that rebuilds the API and automatically submits a commit/PR, or you could add a test function that rebuilds the API and checks whether it is identical to the existing one. If not, pytest will report a failure and you'll know that you have to rebuild the API.

**Comment by m-stclair** [comment] 2021-08-12 20:15
there's an apparent regression in `pydoc-markdown` preventing me from automating this, so I'm putting a pin in this for now. if the issue isn't resolved in a couple of weeks, I'll switch to some other documentation-generating system.

**Comment by m-stclair** [comment] 2021-09-07 21:24
doc freshness test added:  cf0c99b

**Closed as completed by m-stclair** 2021-09-07 21:24 UTC
